services:
    wed:
        image: caddy
        ports:
            - "8083:80"
    web:
        image: litespeedtech/openlitespeed:latest
        ports:
        - "8084:80"
        volumes:
        - ./html:/usr/local/lsws/Example/html
